apiVersion: v1
kind: Pod
metadata:
  name: oom-pod
spec:
  restartPolicy: Always
  containers:
    - name: memory-hog
      image: polinux/stress:latest
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
